# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  newversion:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Bump build version
      id: bump
      uses: vers-one/dotnet-project-version-updater@v1.6
      with:
        file: "src/Voyager.DBConnection/Voyager.DBConnection.csproj"
        version: bump-build

    - run: |
             git branch
             git config user.name "AndrzejSwistowski"
             git config user.email "andrzej.swistowski@voyager.pl"   
             git add .
             git commit -m "Bump project version to ${{ steps.bump.outputs.newVersion }}"
             git push 

  build:
    runs-on: ubuntu-latest
    needs: newversion
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - run: git pull
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Voyager-Source
      run: dotnet nuget add source "https://nuget.pkg.github.com/Voyager-Poland/index.json" -n Voyager-Poland -u ${{secrets.VOY_ACTIONLOGIN}} -p ${{secrets.VOY_ACTIONLOGINPASS}} --store-password-in-clear-text
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore  -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal  -c Release
    - name: Pack
      run: dotnet pack --no-restore --no-build -c Release ${{ github.workspace }}/src/Voyager.DBConnection/Voyager.DBConnection.csproj
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: DBConnection

        path: ${{ github.workspace }}/src/Voyager.DBConnection/bin/Release/*.nupkg 
        compression-level: 0	
        retention-days: 1
        overwrite: true

    # - name: upload to Nuget.org
    #   uses: brandedoutcast/publish-nuget@v2.5.2
    #   with:
    #     PROJECT_FILE_PATH: ${{ github.workspace }}/src/Voyager.DBConnection/Voyager.DBConnection.csproj
    #     NUGET_KEY: ${{secrets.VOY_AND_API_KEY}}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Voyager-Source
        run: dotnet nuget add source "https://nuget.pkg.github.com/Voyager-Poland/index.json" -n Voyager-Poland -u ${{secrets.VOY_ACTIONLOGIN}} -p ${{secrets.VOY_ACTIONLOGINPASS}} --store-password-in-clear-text        
 
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: DBConnection
      - name: Publish the package to GPR
        run: dotnet nuget push ${{ github.workspace }}/*.nupkg -s Voyager-Poland  --skip-duplicate
      - name: Push NuGet package
        run: dotnet nuget push  ${{ github.workspace }}/*.nupkg --api-key ${{secrets.VOY_AND_API_KEY}} --source https://api.nuget.org/v3/index.json
  
